### ISSUE TITLE
loss_std resulting in complex number and breaking Tensorboard

### ISSUE THREAD

**Issue by fernandocamargoti** [ecs-vlc/torchbearer#290] opened 2018-08-09 11:22 UTC
I'm using torchbearer with PyTorch 0.4 and TensorboardX 1.2. Previously, I was using PyTorch 0.4.1, but I had to downgrade to use the TensorboardX because of a incompatibility with them. After adding the Tensorboard callback, the following error is raised after training for some time:

{TypeError}can't convert complex to float

When debugging, I noticed that the add_scalar() of TensorboardX tried to convert the scalar to float and, somehow, the val_loss_std was a complex number. Is there and error in how the std is calculated in order to result in a complex number?

**Comment by MattPainter01** [comment] 2018-08-09 12:37
@fernandocamargoti Thanks for the issue. 

I had a look at the std calculation and I can see that it would go complex if the losses are extremely small, for example, in my testing I get a complex number if I calculate the std([1e-30, 1e-30]). I think pytorch float tensors default to single precision, so this is probably some underflow error.

We should definitely have a check for this and at least return -1 or something similar instead of blindly returning a complex number. I'll make this change now. 

 Are your validation losses very small or do you think the problem is elsewhere?

**Comment by MattPainter01** [comment] 2018-08-09 14:20
Does the error still occur when you have more than 1 validation sample? 

For single samples or multiple samples with the same value then precision errors casting from pytorch floats to python floats can give us negative variances.

For the moment I'll set it to return a variance of 0 for these situations - checkout branch fix/std_complex in the meantime until we merge this.

**Comment by ethanwharris** [comment] 2018-08-13 13:48
Closed by #296

**Closed by ethanwharris** 2018-08-13 13:48 UTC
Labels: bug
